'use strict';

const { describe, it, before } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// All 31 roles that must be generated
const ALL_31_ROLES = [
  'planner', 'executor', 'reviewer', 'verifier', 'orchestrator',
  'wave-researcher', 'wave-planner', 'job-planner', 'job-executor',
  'unit-tester', 'bug-hunter', 'devils-advocate', 'judge',
  'bugfix', 'uat', 'merger',
  'research-stack', 'research-features', 'research-architecture',
  'research-pitfalls', 'research-oversights', 'research-synthesizer',
  'roadmapper', 'codebase-synthesizer', 'context-generator', 'set-planner',
  'plan-verifier', 'wave-analyzer', 'scoper',
  'set-merger', 'conflict-resolver',
];

// Per-role core module mapping (must match production ROLE_CORE_MAP in rapid-tools.cjs)
// Updated for 3-module core: identity, returns, conventions
const EXPECTED_ROLE_CORE_MAP = {
  'planner':              ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
  'executor':             ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
  'reviewer':             ['core-identity.md', 'core-returns.md'],
  'verifier':             ['core-identity.md', 'core-returns.md'],
  'orchestrator':         ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
  'wave-researcher':      ['core-identity.md', 'core-returns.md'],
  'wave-planner':         ['core-identity.md', 'core-returns.md'],
  'job-planner':          ['core-identity.md', 'core-returns.md'],
  'set-planner':          ['core-identity.md', 'core-returns.md'],
  'job-executor':         ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
  'bugfix':               ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
  'merger':               ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
  'unit-tester':          ['core-identity.md', 'core-returns.md'],
  'bug-hunter':           ['core-identity.md', 'core-returns.md'],
  'devils-advocate':      ['core-identity.md', 'core-returns.md'],
  'judge':                ['core-identity.md', 'core-returns.md'],
  'uat':                  ['core-identity.md', 'core-returns.md'],
  'codebase-synthesizer': ['core-identity.md', 'core-returns.md'],
  'context-generator':    ['core-identity.md', 'core-returns.md'],
  'research-stack':       ['core-identity.md', 'core-returns.md'],
  'research-features':    ['core-identity.md', 'core-returns.md'],
  'research-architecture':['core-identity.md', 'core-returns.md'],
  'research-pitfalls':    ['core-identity.md', 'core-returns.md'],
  'research-oversights':  ['core-identity.md', 'core-returns.md'],
  'research-synthesizer': ['core-identity.md', 'core-returns.md'],
  'roadmapper':           ['core-identity.md', 'core-returns.md'],
  'plan-verifier':        ['core-identity.md', 'core-returns.md'],
  'wave-analyzer':        ['core-identity.md', 'core-returns.md'],
  'scoper':               ['core-identity.md', 'core-returns.md'],
  'set-merger':           ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
  'conflict-resolver':    ['core-identity.md', 'core-conventions.md', 'core-returns.md'],
};

const rapidToolsPath = path.join(__dirname, '..', 'bin', 'rapid-tools.cjs');
const agentsDir = path.join(__dirname, '..', '..', 'agents');

describe('build-agents', () => {
  before(() => {
    // Run build-agents to ensure agents/ is populated
    execSync(`node "${rapidToolsPath}" build-agents`, { cwd: path.join(__dirname, '..', '..') });
  });

  describe('agent file generation', () => {
    it('generates exactly 31 .md files', () => {
      const mdFiles = fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'));
      assert.equal(mdFiles.length, 31, `Expected 31 .md files in agents/, got ${mdFiles.length}`);
    });

    it('generates a file for each of the 31 roles', () => {
      for (const role of ALL_31_ROLES) {
        const filePath = path.join(agentsDir, `rapid-${role}.md`);
        assert.ok(fs.existsSync(filePath), `Missing agent file: rapid-${role}.md`);
      }
    });
  });

  describe('frontmatter validation', () => {
    it('each generated file starts with GENERATED comment then YAML frontmatter', () => {
      const files = fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'));
      for (const file of files) {
        const content = fs.readFileSync(path.join(agentsDir, file), 'utf-8');
        assert.ok(
          content.startsWith('<!-- GENERATED by build-agents'),
          `${file} should start with GENERATED comment, got: ${content.substring(0, 60)}`
        );

        const fmStart = content.indexOf('---');
        const fmEnd = content.indexOf('---', fmStart + 3);
        assert.ok(fmStart !== -1 && fmEnd !== -1, `${file} should have YAML frontmatter delimiters`);

        const frontmatter = content.substring(fmStart, fmEnd + 3);
        assert.ok(frontmatter.includes('name:'), `${file} frontmatter should have name field`);
        assert.ok(frontmatter.includes('description:'), `${file} frontmatter should have description field`);
        assert.ok(frontmatter.includes('tools:'), `${file} frontmatter should have tools field`);
        assert.ok(frontmatter.includes('model:'), `${file} frontmatter should have model field`);
        assert.ok(frontmatter.includes('color:'), `${file} frontmatter should have color field`);
      }
    });

    it('no generated file uses fallback color "default"', () => {
      for (const role of ALL_31_ROLES) {
        const content = fs.readFileSync(path.join(agentsDir, `rapid-${role}.md`), 'utf-8');
        const fmStart = content.indexOf('---');
        const fmEnd = content.indexOf('---', fmStart + 3);
        const fm = content.substring(fmStart, fmEnd + 3);
        assert.ok(
          !fm.includes('color: default'),
          `Role "${role}" is using the default color fallback -- needs explicit ROLE_COLORS entry`
        );
      }
    });

    it('no generated file uses generic fallback description', () => {
      for (const role of ALL_31_ROLES) {
        const content = fs.readFileSync(path.join(agentsDir, `rapid-${role}.md`), 'utf-8');
        const fmStart = content.indexOf('---');
        const fmEnd = content.indexOf('---', fmStart + 3);
        const fm = content.substring(fmStart, fmEnd + 3);
        const genericPattern = new RegExp(`description: RAPID ${role} agent\\n`);
        assert.ok(
          !genericPattern.test(fm),
          `Role "${role}" is using the generic description fallback -- needs explicit ROLE_DESCRIPTIONS entry`
        );
      }
    });
  });

  describe('core module inclusion', () => {
    it('each generated file contains correct core module XML tags per ROLE_CORE_MAP', () => {
      for (const [role, coreModules] of Object.entries(EXPECTED_ROLE_CORE_MAP)) {
        const filePath = path.join(agentsDir, `rapid-${role}.md`);
        const content = fs.readFileSync(filePath, 'utf-8');

        for (const mod of coreModules) {
          const tag = mod.replace('.md', '').replace('core-', '');
          assert.ok(
            content.includes(`<${tag}>`),
            `rapid-${role}.md should contain <${tag}> tag (from ${mod})`
          );
          assert.ok(
            content.includes(`</${tag}>`),
            `rapid-${role}.md should contain </${tag}> closing tag (from ${mod})`
          );
        }

        // Verify it does NOT contain core modules it shouldn't
        const allCoreTags = ['identity', 'returns', 'conventions'];
        const expectedTags = coreModules.map(m => m.replace('.md', '').replace('core-', ''));
        for (const tag of allCoreTags) {
          if (!expectedTags.includes(tag)) {
            assert.ok(
              !content.includes(`<${tag}>`),
              `rapid-${role}.md should NOT contain <${tag}> tag`
            );
          }
        }
      }
    });

    it('each generated file contains a <role> tag', () => {
      const files = fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'));
      for (const file of files) {
        const content = fs.readFileSync(path.join(agentsDir, file), 'utf-8');
        assert.ok(content.includes('<role>'), `${file} should contain <role> tag`);
        assert.ok(content.includes('</role>'), `${file} should contain </role> closing tag`);
      }
    });
  });

  describe('tool doc injection', () => {
    it('rapid-executor.md contains <tools> section with expected commands', () => {
      const content = fs.readFileSync(path.join(agentsDir, 'rapid-executor.md'), 'utf-8');
      assert.ok(content.includes('<tools>'), 'rapid-executor.md should contain <tools> tag');
      assert.ok(content.includes('</tools>'), 'rapid-executor.md should contain </tools> tag');
      assert.ok(content.includes('state-get:'), 'rapid-executor.md <tools> should contain state-get command');
      assert.ok(content.includes('state-transition-set:'), 'rapid-executor.md <tools> should contain state-transition-set command');
    });

    it('roles without CLI commands have no <tools> section', () => {
      const content = fs.readFileSync(path.join(agentsDir, 'rapid-research-synthesizer.md'), 'utf-8');
      assert.ok(
        !content.includes('<tools>'),
        'rapid-research-synthesizer.md should NOT contain <tools> tag (no CLI commands)'
      );
    });

    it('<tools> section appears between core modules and <role> tag', () => {
      const content = fs.readFileSync(path.join(agentsDir, 'rapid-executor.md'), 'utf-8');
      const identityEnd = content.indexOf('</identity>');
      const toolsStart = content.indexOf('<tools>');
      const roleStart = content.indexOf('<role>');

      assert.ok(identityEnd !== -1, 'rapid-executor.md should have </identity>');
      assert.ok(toolsStart !== -1, 'rapid-executor.md should have <tools>');
      assert.ok(roleStart !== -1, 'rapid-executor.md should have <role>');

      assert.ok(
        toolsStart > identityEnd,
        '<tools> should appear after </identity>'
      );
      assert.ok(
        toolsStart < roleStart,
        '<tools> should appear before <role>'
      );

      const returnsStart = content.indexOf('<returns>');
      assert.ok(returnsStart !== -1, 'rapid-executor.md should have <returns>');
      assert.ok(
        returnsStart > roleStart,
        '<returns> should appear after <role> (returns is the last static section per PROMPT-SCHEMA.md)'
      );
    });
  });

  describe('XML structure per PROMPT-SCHEMA.md', () => {
    it('required XML tags present in every generated agent (identity, role, returns)', () => {
      const files = fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'));
      for (const file of files) {
        const content = fs.readFileSync(path.join(agentsDir, file), 'utf-8');
        assert.ok(content.includes('<identity>'), `${file} should contain <identity> tag`);
        assert.ok(content.includes('</identity>'), `${file} should contain </identity> tag`);
        assert.ok(content.includes('<role>'), `${file} should contain <role> tag`);
        assert.ok(content.includes('</role>'), `${file} should contain </role> tag`);
        assert.ok(content.includes('<returns>'), `${file} should contain <returns> tag`);
        assert.ok(content.includes('</returns>'), `${file} should contain </returns> tag`);
      }
    });
  });

  describe('agent size limits', () => {
    it('no generated file exceeds 15KB (except known oversized agents)', () => {
      const KNOWN_OVERSIZED = ['rapid-planner.md', 'rapid-plan-verifier.md', 'rapid-set-merger.md', 'rapid-merger.md'];
      const files = fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'));
      for (const file of files) {
        const content = fs.readFileSync(path.join(agentsDir, file), 'utf-8');
        const sizeBytes = Buffer.byteLength(content, 'utf-8');
        if (KNOWN_OVERSIZED.includes(file)) {
          assert.ok(
            sizeBytes <= 25600,
            `${file} is ${(sizeBytes / 1024).toFixed(1)}KB, exceeds even generous 25KB limit`
          );
          continue;
        }
        assert.ok(
          sizeBytes <= 15360,
          `${file} is ${(sizeBytes / 1024).toFixed(1)}KB, exceeds 15KB limit`
        );
      }
    });
  });
});
