'use strict';

const fs = require('fs');
const path = require('path');
const { createInitialState } = require('./state-machine.cjs');
const { getVersion } = require('./version.cjs');

/**
 * Generate PROJECT.md content from project configuration.
 *
 * @param {Object} opts
 * @param {string} opts.name - Project name
 * @param {string} opts.description - Project description
 * @param {number} opts.teamSize - Number of team members
 * @returns {string} Markdown content for PROJECT.md
 */
function generateProjectMd({ name, description, teamSize }) {
  const createdDate = new Date().toISOString().split('T')[0];
  const parallelCapacity = Math.max(1, Math.floor(teamSize * 1.5));

  return `# ${name}

## Description

${description}

## Team Configuration

- **Team Size:** ${teamSize}
- **Parallel Capacity:** ${parallelCapacity} (concurrent work streams)

## Key Decisions

| Date | Decision | Rationale |
|------|----------|-----------|
| | | |

## Project Info

- **Created:** ${createdDate}
- **Status:** Active
`;
}

/**
 * Generate STATE.md content with YAML frontmatter and initial state sections.
 *
 * @returns {string} Markdown content for STATE.md
 */
function generateStateMd() {
  const lastUpdated = new Date().toISOString();

  return `---
rapid_state_version: 1.0
milestone: v1.0
milestone_name: milestone
status: initialized
last_updated: "${lastUpdated}"
progress:
  total_phases: 0
  completed_phases: 0
  total_plans: 0
  completed_plans: 0
---

# Project State

## Current Position

Phase: 0 of 0
Plan: 0 of 0 in current phase
Status: Initialized
Last activity: ${new Date().toISOString().split('T')[0]}

Progress: [░░░░░░░░░░] 0%

## Performance Metrics

**Velocity:**
- Total plans completed: 0
- Average duration: N/A
- Total execution time: 0 hours

*Updated after each plan completion*

## Accumulated Context

### Decisions

None yet.

### Pending Todos

None yet.

### Blockers/Concerns

None yet.

## Session Continuity

Last session: ${new Date().toISOString().split('T')[0]}
Stopped at: Project initialized
Resume file: None
`;
}

/**
 * Generate ROADMAP.md template content.
 *
 * @param {string} projectName - Project name for heading
 * @returns {string} Markdown content for ROADMAP.md
 */
function generateRoadmapMd(projectName) {
  return `# ${projectName} - Roadmap

## Overview

This roadmap tracks the phased development plan for ${projectName}.

## Phases

*No phases defined yet. Use planning to populate phases.*

## Phase Progress

| Phase | Name | Plans | Completed | Status |
|-------|------|-------|-----------|--------|
| | | | | |

## Milestones

- **v1.0** - Initial release

---
*Generated by RAPID*
`;
}

/**
 * Generate REQUIREMENTS.md template content.
 *
 * @param {string} projectName - Project name for heading
 * @returns {string} Markdown content for REQUIREMENTS.md
 */
function generateRequirementsMd(projectName) {
  return `# ${projectName} - Requirements

## v1 Requirements

*No requirements defined yet. Use planning to populate requirements.*

## Out of Scope

*Items explicitly excluded from current scope.*

## Traceability

| Requirement ID | Description | Phase | Plan | Status |
|---------------|-------------|-------|------|--------|
| | | | | |

---
*Generated by RAPID*
`;
}

/**
 * Generate default config.json content.
 *
 * @param {Object} [opts={}] - Configuration options
 * @param {string} [opts.name] - Project name
 * @param {string} [opts.model='sonnet'] - Model selection ('opus' or 'sonnet')
 * @param {number} [opts.teamSize=1] - Team size for parallel capacity
 * @returns {string} JSON string for config.json
 */
function generateConfigJson(opts = {}) {
  const soloValue = opts.solo !== undefined ? opts.solo : (opts.teamSize || 1) === 1;
  const config = {
    project: {
      name: opts.name || '',
      version: '0.1.0',
    },
    model: opts.model || 'sonnet',
    planning: {
      max_parallel_sets: Math.max(1, Math.floor((opts.teamSize || 1) * 1.5)),
    },
    solo: soloValue,
  };
  if (opts.testFrameworks && opts.testFrameworks.length > 0) {
    config.testFrameworks = opts.testFrameworks;
  }
  return JSON.stringify(config, null, 2);
}

/**
 * Detect whether a .planning/ directory exists at the given path.
 *
 * @param {string} cwd - Directory to check
 * @returns {{ exists: boolean, files: string[] }}
 */
function detectExisting(cwd) {
  const planningDir = path.join(cwd, '.planning');

  if (!fs.existsSync(planningDir) || !fs.statSync(planningDir).isDirectory()) {
    return { exists: false, files: [] };
  }

  const files = fs.readdirSync(planningDir).filter((f) => {
    const fullPath = path.join(planningDir, f);
    return fs.statSync(fullPath).isFile();
  });

  return { exists: true, files };
}

/**
 * Scaffold a new RAPID project by creating .planning/ with required files.
 *
 * @param {string} cwd - Target directory
 * @param {Object} opts - Project configuration
 * @param {string} opts.name - Project name
 * @param {string} opts.description - Project description
 * @param {number} opts.teamSize - Team size
 * @param {string} [mode='fresh'] - Scaffold mode: 'fresh', 'reinitialize', 'upgrade', 'cancel'
 * @returns {Object} Result with created/skipped/cancelled/backed_up_to fields
 */
function scaffoldProject(cwd, opts, mode = 'fresh') {
  if (mode === 'cancel') {
    return { cancelled: true };
  }

  const planningDir = path.join(cwd, '.planning');

  // File definitions: filename -> generator function
  const fileGenerators = {
    'PROJECT.md': () => generateProjectMd(opts),
    'STATE.md': () => generateStateMd(),
    'ROADMAP.md': () => generateRoadmapMd(opts.name),
    'REQUIREMENTS.md': () => generateRequirementsMd(opts.name),
    'config.json': () => generateConfigJson(opts),
    'STATE.json': () => JSON.stringify(createInitialState(opts.name, 'v1.0', getVersion()), null, 2),
  };

  // Helper: ensure research directory exists inside planningDir
  const ensureResearchDir = () => {
    const researchDir = path.join(planningDir, 'research');
    fs.mkdirSync(researchDir, { recursive: true });
  };

  if (mode === 'reinitialize') {
    // Back up existing .planning/ if it exists
    let backedUpTo = null;
    if (fs.existsSync(planningDir)) {
      const timestamp = Date.now();
      const backupDir = path.join(cwd, `.planning.backup.${timestamp}`);
      fs.cpSync(planningDir, backupDir, { recursive: true });
      fs.rmSync(planningDir, { recursive: true, force: true });
      backedUpTo = backupDir;
    }

    // Create fresh
    fs.mkdirSync(planningDir, { recursive: true });
    ensureResearchDir();
    const created = [];
    for (const [filename, generator] of Object.entries(fileGenerators)) {
      fs.writeFileSync(path.join(planningDir, filename), generator());
      created.push(filename);
    }

    const result = { created, skipped: [] };
    if (backedUpTo) {
      result.backed_up_to = backedUpTo;
    }
    return result;
  }

  if (mode === 'upgrade') {
    // Create .planning/ if it doesn't exist
    if (!fs.existsSync(planningDir)) {
      fs.mkdirSync(planningDir, { recursive: true });
    }
    ensureResearchDir();

    const created = [];
    const skipped = [];
    for (const [filename, generator] of Object.entries(fileGenerators)) {
      const filePath = path.join(planningDir, filename);
      if (fs.existsSync(filePath)) {
        skipped.push(filename);
      } else {
        fs.writeFileSync(filePath, generator());
        created.push(filename);
      }
    }

    return { created, skipped };
  }

  // Default: fresh mode
  fs.mkdirSync(planningDir, { recursive: true });
  ensureResearchDir();
  const created = [];
  for (const [filename, generator] of Object.entries(fileGenerators)) {
    fs.writeFileSync(path.join(planningDir, filename), generator());
    created.push(filename);
  }

  return { created, skipped: [] };
}

module.exports = {
  scaffoldProject,
  detectExisting,
  generateProjectMd,
  generateStateMd,
  generateRoadmapMd,
  generateRequirementsMd,
  generateConfigJson,
};
